version: '3.8'

services:
  zumi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zumi-backend
    networks:
      - api_back_db
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      BACKEND_PORT: 3001
      BACKEND_ADDRESS: '::'
      DATABASE_CONNECTION_STRING: postgresql://user:1234@postgres:5432/shadow_test?schema=draft_app
      ACCESS_SECRET: TESTETSE
      REFRESH_SECRET: TESTETSE
      ACCESS_PERIOD: 1d
      REFRESH_PERIOD: 5d
      MAIL_HOST: smtp.ethereal.email
      MAIL_CREDENTIALS_LOGIN: loraine.wintheiser@ethereal.email
      MAIL_CREDENTIALS_PASSWORD: aT5e5EWdX2MAKewsyJ
      MAIL_PORT: 587
      MAIL_SECURITY_FLAG: false
      COOKIE_SECRET: test-secret
    command: ['pnpm', 'pm2:prod']
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shadow_test
      PG_SCHEMA: draft_app
    networks:
      - api_back_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

networks:
  api_back_db:
    driver: bridge
    name: api_back_db
